// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface LanguageInfo {
    "language_name": string;
    "language_code": string;
    "textmap_path": string;
    "translation_progress": string;
    "translator": string;
    "last_updated": string;
    "version": string;
}
