// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BaiduLogout() {
  return window['go']['service']['App']['BaiduLogout']();
}

export function BaiduQRLogin(arg1, arg2) {
  return window['go']['service']['App']['BaiduQRLogin'](arg1, arg2);
}

export function CheckOShinDUpdate() {
  return window['go']['service']['App']['CheckOShinDUpdate']();
}

export function CheckUpdate() {
  return window['go']['service']['App']['CheckUpdate']();
}

export function GetALLLang() {
  return window['go']['service']['App']['GetALLLang']();
}

export function GetAppVersion() {
  return window['go']['service']['App']['GetAppVersion']();
}

export function GetBaiduDownloadLink(arg1) {
  return window['go']['service']['App']['GetBaiduDownloadLink'](arg1);
}

export function GetBaiduDownloadLinkRemote(arg1) {
  return window['go']['service']['App']['GetBaiduDownloadLinkRemote'](arg1);
}

export function GetBaiduFileList(arg1) {
  return window['go']['service']['App']['GetBaiduFileList'](arg1);
}

export function GetBaiduQR() {
  return window['go']['service']['App']['GetBaiduQR']();
}

export function GetBaiduQuota() {
  return window['go']['service']['App']['GetBaiduQuota']();
}

export function GetCurrentLang() {
  return window['go']['service']['App']['GetCurrentLang']();
}

export function GetLangPack() {
  return window['go']['service']['App']['GetLangPack']();
}

export function GetLangTextMap() {
  return window['go']['service']['App']['GetLangTextMap']();
}

export function GetLogFileContent(arg1) {
  return window['go']['service']['App']['GetLogFileContent'](arg1);
}

export function GetLogFiles() {
  return window['go']['service']['App']['GetLogFiles']();
}

export function GetLogLevel() {
  return window['go']['service']['App']['GetLogLevel']();
}

export function GetOShinDVersion() {
  return window['go']['service']['App']['GetOShinDVersion']();
}

export function GetProcessName() {
  return window['go']['service']['App']['GetProcessName']();
}

export function GetSettings() {
  return window['go']['service']['App']['GetSettings']();
}

export function GetSystemInfo() {
  return window['go']['service']['App']['GetSystemInfo']();
}

export function LoginWithCookie(arg1, arg2, arg3) {
  return window['go']['service']['App']['LoginWithCookie'](arg1, arg2, arg3);
}

export function Notify(arg1, arg2) {
  return window['go']['service']['App']['Notify'](arg1, arg2);
}

export function OpenFileSelect() {
  return window['go']['service']['App']['OpenFileSelect']();
}

export function OpenFolderSelect() {
  return window['go']['service']['App']['OpenFolderSelect']();
}

export function PollBaiduQR(arg1) {
  return window['go']['service']['App']['PollBaiduQR'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['service']['App']['ReadFileContent'](arg1);
}

export function RestoreLogin() {
  return window['go']['service']['App']['RestoreLogin']();
}

export function SaveFileSelect() {
  return window['go']['service']['App']['SaveFileSelect']();
}

export function SaveSettings(arg1) {
  return window['go']['service']['App']['SaveSettings'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['service']['App']['SetLanguage'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['service']['App']['SetLogLevel'](arg1);
}

export function WindowClose() {
  return window['go']['service']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['service']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['service']['App']['WindowToggleMaximise']();
}

export function WriteFileContent(arg1, arg2) {
  return window['go']['service']['App']['WriteFileContent'](arg1, arg2);
}
