// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {global} from '../models';

export function BaiduLogout():Promise<boolean>;

export function BaiduQRLogin(arg1:string,arg2:boolean):Promise<service.BaiduLoginResult>;

export function CheckOShinDUpdate():Promise<service.OShinDUpdateResult>;

export function CheckUpdate():Promise<service.UpdateCheckResult>;

export function GetALLLang():Promise<Array<global.LanguageInfo>>;

export function GetAppVersion():Promise<string>;

export function GetBaiduDownloadLink(arg1:number):Promise<service.BaiduDownloadLinkResult>;

export function GetBaiduDownloadLinkRemote(arg1:number):Promise<service.BaiduDownloadLinkResult>;

export function GetBaiduFileList(arg1:string):Promise<service.BaiduFileListResult>;

export function GetBaiduQR():Promise<service.BaiduQRCode>;

export function GetBaiduQuota():Promise<service.BaiduQuotaInfo>;

export function GetCurrentLang():Promise<string>;

export function GetLangPack():Promise<global.LanguagePack>;

export function GetLangTextMap():Promise<Record<string, string>>;

export function GetLogFileContent(arg1:string):Promise<string>;

export function GetLogFiles():Promise<Array<string>>;

export function GetLogLevel():Promise<string>;

export function GetOShinDVersion():Promise<service.OShinDInfo>;

export function GetProcessName():Promise<string>;

export function GetSettings():Promise<service.AppSettings>;

export function GetSystemInfo():Promise<service.SystemInfo>;

export function LoginWithCookie(arg1:string,arg2:string,arg3:boolean):Promise<service.BaiduLoginResult>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenFileSelect():Promise<string>;

export function OpenFolderSelect():Promise<string>;

export function PollBaiduQR(arg1:string):Promise<service.BaiduPollResult>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RestoreLogin():Promise<service.BaiduLoginResult>;

export function SaveFileSelect():Promise<string>;

export function SaveSettings(arg1:service.AppSettings):Promise<string>;

export function SetLanguage(arg1:string):Promise<boolean>;

export function SetLogLevel(arg1:string):Promise<boolean>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;

export function WriteFileContent(arg1:string,arg2:string):Promise<boolean>;
