// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 前端可调用的服务。
 * v3 的 service 不再需要保存 context：窗口、对话框、事件都直接挂在 app 实例上，
 * 因此这里持有 *application.App 引用，运行期由 main 通过构造函数注入。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as global$0 from "../global/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BaiduLogout 退出登录，清除凭证（同时删除本地保存的登录信息）
 */
export function BaiduLogout(): $CancellablePromise<boolean> {
    return $Call.ByID(3461244360);
}

/**
 * BaiduQRLogin 使用扫码得到的凭证 v 换取登录 Cookie，并验证网盘登录状态
 * rememberLogin 为 true 时登录成功后保存登录信息到本地
 */
export function BaiduQRLogin(v: string, rememberLogin: boolean): $CancellablePromise<$models.BaiduLoginResult | null> {
    return $Call.ByID(3810780330, v, rememberLogin);
}

/**
 * CancelDownloadTask 取消任务（保留已下载内容）
 */
export function CancelDownloadTask(taskID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3870940636, taskID);
}

/**
 * CheckOShinDUpdate 检查组件更新：
 *   - 已安装：compareVersion 真实对比
 *   - 未安装：仅查询最新版本供展示（视为可安装）
 */
export function CheckOShinDUpdate(): $CancellablePromise<$models.OShinDUpdateResult> {
    return $Call.ByID(2051626723);
}

/**
 * CheckUpdate 请求 GitHub Releases API 获取最新版本并对比
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateCheckResult> {
    return $Call.ByID(3225912800);
}

export function GetALLLang(): $CancellablePromise<global$0.LanguageInfo[] | null> {
    return $Call.ByID(2501386300);
}

/**
 * GetAppVersion 返回当前版本号
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1794640196);
}

/**
 * GetBaiduDownloadLink 本地解析文件下载直链（filemetas + rand 签名 + Location 跟踪）
 */
export function GetBaiduDownloadLink(fsID: number): $CancellablePromise<$models.BaiduDownloadLinkResult | null> {
    return $Call.ByID(12410344, fsID);
}

/**
 * GetBaiduDownloadLinkRemote 远程解析文件下载直链（加速链接，需在设置中配置）
 * 未配置加速链接时返回失败；对齐 KinhWebEO handler/down.go downRemote
 */
export function GetBaiduDownloadLinkRemote(fsID: number): $CancellablePromise<$models.BaiduDownloadLinkResult | null> {
    return $Call.ByID(1621958110, fsID);
}

export function GetBaiduFileList(dir: string): $CancellablePromise<$models.BaiduFileListResult | null> {
    return $Call.ByID(4080528170, dir);
}

/**
 * GetBaiduQR 获取百度登录二维码，返回 base64 图片与轮询凭证
 */
export function GetBaiduQR(): $CancellablePromise<$models.BaiduQRCode | null> {
    return $Call.ByID(3711376683);
}

/**
 * GetBaiduQuota 获取网盘容量信息（GET /api/quota?checkfree=1&checkexpire=1）
 */
export function GetBaiduQuota(): $CancellablePromise<$models.BaiduQuotaInfo | null> {
    return $Call.ByID(588009712);
}

export function GetCurrentLang(): $CancellablePromise<string> {
    return $Call.ByID(3813649274);
}

/**
 * GetDownloadTasks 返回任务列表（台账元数据 + 组件实时状态合并）
 */
export function GetDownloadTasks(): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(1351277853);
}

export function GetLangPack(): $CancellablePromise<global$0.LanguagePack | null> {
    return $Call.ByID(1209251452);
}

export function GetLangTextMap(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2091995996);
}

export function GetLogFileContent(filename: string): $CancellablePromise<string> {
    return $Call.ByID(2999618164, filename);
}

export function GetLogFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(163866400);
}

export function GetLogLevel(): $CancellablePromise<string> {
    return $Call.ByID(979683821);
}

/**
 * GetOShinDVersion 返回下载组件当前信息
 */
export function GetOShinDVersion(): $CancellablePromise<$models.OShinDInfo> {
    return $Call.ByID(3641222686);
}

export function GetProcessName(): $CancellablePromise<string> {
    return $Call.ByID(2714128149);
}

/**
 * GetSettings 返回当前设置副本（前端读取入口）
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1857466324);
}

export function GetSystemInfo(): $CancellablePromise<$models.SystemInfo> {
    return $Call.ByID(1838409332);
}

/**
 * LoginWithCookie 使用用户手动填写的 Cookie 登录（仅需 BDUSS 与 PTOKEN，STOKEN 由 PTOKEN 换取）
 * rememberLogin 为 true 时登录成功后保存登录信息到本地
 */
export function LoginWithCookie(bduss: string, ptoken: string, rememberLogin: boolean): $CancellablePromise<$models.BaiduLoginResult | null> {
    return $Call.ByID(1310908458, bduss, ptoken, rememberLogin);
}

export function Notify(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(2340632202, title, message);
}

export function OpenFileSelect(): $CancellablePromise<string> {
    return $Call.ByID(100762981);
}

export function OpenFolderSelect(): $CancellablePromise<string> {
    return $Call.ByID(1985253079);
}

/**
 * PauseDownloadTask 暂停任务（组件保存断点状态，可恢复）
 */
export function PauseDownloadTask(taskID: string): $CancellablePromise<boolean> {
    return $Call.ByID(4289001386, taskID);
}

/**
 * PollBaiduQR 执行一次扫码状态轮询（前端循环调用，每次为一次长轮询请求）
 * status: waiting | scanned | success | error | network_error
 * network_error 表示网络异常（区别于二维码过期），由前端决定是否继续轮询
 */
export function PollBaiduQR(sign: string): $CancellablePromise<$models.BaiduPollResult | null> {
    return $Call.ByID(4167141106, sign);
}

export function ReadFileContent(path: string): $CancellablePromise<string> {
    return $Call.ByID(3026439562, path);
}

/**
 * RemoveDownloadTask 移除任务并删除台账条目
 * deleteFiles 为 true 时同时删除下载产物（成品文件 + .tmp 临时文件 + .oshin 断点状态）。
 * 无论是否删除文件，都先取消并移除组件侧任务（CancelTask + RemoveTask 双重保证），
 * 防止后台继续空跑下载。
 */
export function RemoveDownloadTask(taskID: string, deleteFiles: boolean): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(357420622, taskID, deleteFiles);
}

/**
 * RestoreLogin 使用本地保存的登录信息自动登录（含 STOKEN 失效时刷新一次重试）
 */
export function RestoreLogin(): $CancellablePromise<$models.BaiduLoginResult | null> {
    return $Call.ByID(3012888636);
}

/**
 * ResumeDownloadTask 恢复暂停/失败的任务
 * 组件侧移除旧任务并重新提交（自动检测 .oshin 断点状态），返回新任务 ID，
 * 台账条目需同步替换 ID，否则后续轮询查不到状态
 */
export function ResumeDownloadTask(taskID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3249342345, taskID);
}

export function SaveFileSelect(): $CancellablePromise<string> {
    return $Call.ByID(2720509348);
}

/**
 * SaveSettings 保存设置并立即生效，返回错误信息（空串为成功）
 * 
 * TODO(托盘功能实现时)：close_action 的 tray 选项当前仅存值未生效——
 *  1. main.go 需注册系统托盘（wails v2 无内置托盘，需引入第三方 systray 类库）
 *  2. WindowClose 按设置分流：exit 直接退出，tray 隐藏窗口到托盘
 *  3. 托盘菜单：显示主窗口 / 退出，并处理二次启动唤起
 */
export function SaveSettings(settings: $models.AppSettings): $CancellablePromise<string> {
    return $Call.ByID(2689818911, settings);
}

export function SetLanguage(langCode: string): $CancellablePromise<boolean> {
    return $Call.ByID(1288891019, langCode);
}

export function SetLogLevel(level: string): $CancellablePromise<boolean> {
    return $Call.ByID(702413929, level);
}

/**
 * SubmitDownload 解析并提交下载任务（组件存在时可用）
 * fsID >= 0 表示网盘文件（先解析直链），url 非空表示自定义任务直接下载
 */
export function SubmitDownload(url: string, fileName: string, fsID: number): $CancellablePromise<$models.DownloadSubmitResult | null> {
    return $Call.ByID(1596279107, url, fileName, fsID);
}

/**
 * SubmitDownloadWithOptions 提交自定义下载任务（组件存在时可用，选项覆盖设置默认值）
 */
export function SubmitDownloadWithOptions(opts: $models.DownloadTaskOptions): $CancellablePromise<$models.DownloadSubmitResult | null> {
    return $Call.ByID(3968366703, opts);
}

export function WindowClose(): $CancellablePromise<void> {
    return $Call.ByID(595349813);
}

export function WindowMinimise(): $CancellablePromise<void> {
    return $Call.ByID(4275373610);
}

export function WindowToggleMaximise(): $CancellablePromise<void> {
    return $Call.ByID(3772691052);
}

export function WriteFileContent(path: string, content: string): $CancellablePromise<boolean> {
    return $Call.ByID(3441468705, path, content);
}
