// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 前端可调用的服务。
 * v3 的 service 不再需要保存 context：窗口、对话框、事件都直接挂在 app 实例上，
 * 因此这里持有 *application.App 引用，运行期由 main 通过构造函数注入。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as global$0 from "../global/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BaiduLogout 退出登录，清除凭证（同时删除本地保存的登录信息）
 */
export function BaiduLogout(): $CancellablePromise<boolean> {
    return $Call.ByID(3461244360);
}

/**
 * BaiduQRLogin 使用扫码得到的凭证 v 换取登录 Cookie，并验证网盘登录状态
 * rememberLogin 为 true 时登录成功后保存登录信息到本地
 */
export function BaiduQRLogin(v: string, rememberLogin: boolean): $CancellablePromise<$models.BaiduLoginResult | null> {
    return $Call.ByID(3810780330, v, rememberLogin);
}

/**
 * CancelDownloadTask 取消任务（保留已下载内容）。
 * 排队任务（queued-<seq> 占位 ID）引擎侧无句柄，前端不对其发 Cancel，
 * 移除走 RemoveDownloadTask
 */
export function CancelDownloadTask(taskID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3870940636, taskID);
}

/**
 * CheckUpdate 请求 GitHub Releases API 获取最新版本并对比
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateCheckResult> {
    return $Call.ByID(3225912800);
}

export function GetALLLang(): $CancellablePromise<global$0.LanguageInfo[] | null> {
    return $Call.ByID(2501386300);
}

/**
 * GetAppVersion 返回当前版本号
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1794640196);
}

/**
 * GetBaiduDownloadLink 本地解析文件下载直链（filemetas + rand 签名 + Location 跟踪）
 */
export function GetBaiduDownloadLink(fsID: number): $CancellablePromise<$models.BaiduDownloadLinkResult | null> {
    return $Call.ByID(12410344, fsID);
}

/**
 * GetBaiduDownloadLinkRemote 远程解析文件下载直链（加速链接，需在设置中配置）
 * 未配置加速链接时返回失败；对齐 KinhWebEO handler/down.go downRemote
 */
export function GetBaiduDownloadLinkRemote(fsID: number): $CancellablePromise<$models.BaiduDownloadLinkResult | null> {
    return $Call.ByID(1621958110, fsID);
}

export function GetBaiduFileList(dir: string): $CancellablePromise<$models.BaiduFileListResult | null> {
    return $Call.ByID(4080528170, dir);
}

/**
 * GetBaiduQR 获取百度登录二维码，返回 base64 图片与轮询凭证
 */
export function GetBaiduQR(): $CancellablePromise<$models.BaiduQRCode | null> {
    return $Call.ByID(3711376683);
}

/**
 * GetBaiduQuota 获取网盘容量信息（GET /api/quota?checkfree=1&checkexpire=1）
 */
export function GetBaiduQuota(): $CancellablePromise<$models.BaiduQuotaInfo | null> {
    return $Call.ByID(588009712);
}

/**
 * GetDownloadTasks 返回任务列表（台账元数据 + 引擎实时状态合并）
 */
export function GetDownloadTasks(): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(1351277853);
}

export function GetLangTextMap(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2091995996);
}

/**
 * GetOShinDVersion 返回下载引擎信息。
 * 引擎已编译进主程序，不存在「未安装」「加载失败」这一类状态。
 */
export function GetOShinDVersion(): $CancellablePromise<$models.OShinDInfo> {
    return $Call.ByID(3641222686);
}

/**
 * GetSettings 返回当前设置副本（前端读取入口）
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1857466324);
}

/**
 * LoginWithBaiduSMS 使用手机号 + 短信验证码登录。
 * rememberLogin 为 true 时登录成功后保存登录信息到本地。
 */
export function LoginWithBaiduSMS(phone: string, smsCode: string, rememberLogin: boolean): $CancellablePromise<$models.BaiduLoginResult | null> {
    return $Call.ByID(1873538860, phone, smsCode, rememberLogin);
}

/**
 * LoginWithCookie 使用用户手动填写的 Cookie 登录（仅需 BDUSS 与 PTOKEN，STOKEN 由 PTOKEN 换取）
 * rememberLogin 为 true 时登录成功后保存登录信息到本地
 */
export function LoginWithCookie(bduss: string, ptoken: string, rememberLogin: boolean): $CancellablePromise<$models.BaiduLoginResult | null> {
    return $Call.ByID(1310908458, bduss, ptoken, rememberLogin);
}

export function OpenFolderSelect(): $CancellablePromise<string> {
    return $Call.ByID(1985253079);
}

/**
 * PauseDownloadTask 暂停任务（引擎保存断点状态，可恢复）
 */
export function PauseDownloadTask(taskID: string): $CancellablePromise<boolean> {
    return $Call.ByID(4289001386, taskID);
}

/**
 * PollBaiduQR 执行一次扫码状态轮询（前端循环调用，每次为一次长轮询请求）
 * status: waiting | scanned | success | error | network_error
 * network_error 表示网络异常（区别于二维码过期），由前端决定是否继续轮询
 */
export function PollBaiduQR(sign: string): $CancellablePromise<$models.BaiduPollResult | null> {
    return $Call.ByID(4167141106, sign);
}

/**
 * RemoveDownloadTask 移除任务并删除台账条目
 * deleteFiles 为 true 时同时删除下载产物（成品文件 + .tmp 临时文件 + .oshin 断点状态）。
 * 无论是否删除文件，都先取消并移除组件侧任务（CancelTask + RemoveTask 双重保证），
 * 防止后台继续空跑下载。
 */
export function RemoveDownloadTask(taskID: string, deleteFiles: boolean): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(357420622, taskID, deleteFiles);
}

/**
 * ResolveCloseAction 前端询问完成后回传用户选择。
 * remember 为 true 时把选择写入设置，此后关闭不再询问。
 * action 取值：tray（隐藏到托盘）/ exit（退出）/ cancel（取消本次关闭）
 */
export function ResolveCloseAction(action: string, remember: boolean): $CancellablePromise<void> {
    return $Call.ByID(3686731421, action, remember);
}

/**
 * ResolveMultiLink 并发解析文件下载地址（实验性下载入口）。
 * 
 * 对选定渠道**并发发起 count 次解析请求**：百度 API 每次请求都会重新生成
 * 下载地址，因此 N 次请求即得 N 个不同地址（无需去重）。全部请求完成后
 * 统一收集，第一个地址作为主 URL，其余进引擎 MultiSources 多源下载。
 * 
 * ⚠️ 加速链接未配置/已清空时渠道必为 local（multiLinkChannel 内有回落），
 * 绝不会对空地址发起请求；并发调 resolveWithRetry 安全 ——
 * 凭证读写有 credentialMu 保护（baidu_auth.go）。
 */
export function ResolveMultiLink(fsID: number, fileName: string, count: number): $CancellablePromise<$models.MultiLinkResult | null> {
    return $Call.ByID(365341670, fsID, fileName, count);
}

/**
 * RestoreLogin 使用本地保存的登录信息自动登录（含 STOKEN 失效时刷新一次重试）
 */
export function RestoreLogin(): $CancellablePromise<$models.BaiduLoginResult | null> {
    return $Call.ByID(3012888636);
}

/**
 * ResumeDownloadTask 恢复暂停/失败的任务。
 * 引擎侧 ResumeTask 会移除旧任务并重新提交（自动检测 .oshin 断点），
 * 返回新任务 ID，台账条目需同步替换 ID，否则后续轮询查不到状态。
 * 
 * 两类「返回 false」必须区分，否则前端会把「并发满、稍后再说」当成
 * 「恢复失败」并累加重试计数，几轮内就误报「重试耗尽，请手动处理」：
 *   - deferred：并发已满，本次未尝试恢复，不消耗重试次数
 *   - failed：真正恢复失败，消耗一次重试次数
 * 
 * 通过台账条目的 retry_pending 标记把该信息带回给前端（bool 返回值是
 * 既有 bindings 契约，不能改签名）。
 */
export function ResumeDownloadTask(taskID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3249342345, taskID);
}

/**
 * SaveSettings 保存设置并立即生效，返回错误信息（空串为成功）
 */
export function SaveSettings(settings: $models.AppSettings): $CancellablePromise<string> {
    return $Call.ByID(2689818911, settings);
}

/**
 * SendBaiduSMSCode 向指定手机号发送登录短信验证码。
 * verifyCode / vcodeStr / vcodeSign 仅在上一轮返回 need_vcode 时填写：
 * vcodeStr、vcodeSign 原样回传上一轮的值，verifyCode 是用户看图填的字符。
 */
export function SendBaiduSMSCode(phone: string, verifyCode: string, vcodeStr: string, vcodeSign: string): $CancellablePromise<$models.BaiduSMSCodeResult | null> {
    return $Call.ByID(3016266500, phone, verifyCode, vcodeStr, vcodeSign);
}

/**
 * SubmitDownload 解析并提交下载任务（组件存在时可用）
 * fsID >= 0 表示网盘文件（先解析直链），url 非空表示自定义任务直接下载
 */
export function SubmitDownload(url: string, fileName: string, fsID: number): $CancellablePromise<$models.DownloadSubmitResult | null> {
    return $Call.ByID(1596279107, url, fileName, fsID);
}

/**
 * SubmitDownloadWithOptions 提交自定义下载任务（组件存在时可用，选项覆盖设置默认值）
 */
export function SubmitDownloadWithOptions(opts: $models.DownloadTaskOptions): $CancellablePromise<$models.DownloadSubmitResult | null> {
    return $Call.ByID(3968366703, opts);
}

/**
 * WindowClose 请求关闭窗口。
 * 不直接退出，而是走窗口关闭流程交由 close.go 的 hook 按设置分流
 * （直接退出 / 隐藏到托盘 / 询问用户），保证前端按钮与系统关闭走同一条路径
 */
export function WindowClose(): $CancellablePromise<void> {
    return $Call.ByID(595349813);
}

export function WindowMinimise(): $CancellablePromise<void> {
    return $Call.ByID(4275373610);
}

export function WindowToggleMaximise(): $CancellablePromise<void> {
    return $Call.ByID(3772691052);
}
