// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppSettings 应用设置结构，JSON 字段即落盘字段
 */
export interface AppSettings {
    /**
     * 程序设置
     * 语言代码，如 zh-CN
     */
    "language": string;

    /**
     * 点击关闭后的操作：exit / tray（预留）
     */
    "close_action": string;

    /**
     * 下载代理（留空不启用），作用于 OShinD 组件下载与直链请求
     */
    "download_proxy": string;

    /**
     * 下载设置
     * 默认 UA
     */
    "download_user_agent": string;

    /**
     * 默认线程数
     */
    "download_threads": number;

    /**
     * 分片大小（KB，0 表示未设置用默认值）
     */
    "download_chunk_kb": number;

    /**
     * 默认下载目录
     */
    "download_dir": string;

    /**
     * 远程解析加速链接（留空仅本地解析）
     */
    "download_acc_link": string;

    /**
     * 下载失败自动重试次数（0 表示不重试）
     */
    "download_max_retries": number;

    /**
     * 其他
     * 日志等级：debug/info/warn/error
     */
    "log_level": string;
}

/**
 * BaiduDownloadLinkResult 下载地址解析结果（返回给前端）
 */
export interface BaiduDownloadLinkResult {
    "success": boolean;
    "fs_id": number;
    "filename": string;
    "dlink": string;
    "message"?: string;
}

export interface BaiduFileItem {
    "fs_id": number;
    "path": string;
    "filename": string;
    "server_filename": string;
    "size": number;
    "isdir": number;
    "server_mtime": number;
    "category": number;
    "md5"?: string;
}

export interface BaiduFileListResult {
    "success": boolean;
    "dir": string;
    "list": BaiduFileItem[] | null;
    "message"?: string;
}

export interface BaiduLoginResult {
    "success": boolean;
    "username": string;
    "user_id": string;
    "bduss": string;
    "ptoken": string;
    "stoken": string;

    /**
     * 网盘操作用的 bdstoken
     */
    "bd_stoken": string;

    /**
     * 0 无会员 / 1 VIP / 2 SVIP
     */
    "vip_type": number;

    /**
     * 头像
     */
    "photo_url": string;
    "message": string;
}

export interface BaiduPollResult {
    /**
     * waiting | scanned | success | error
     */
    "status": string;

    /**
     * 登录凭证 v（status == success 时有效）
     */
    "v": string;
}

export interface BaiduQRCode {
    /**
     * 二维码图片 Data URL（image/png;base64）
     */
    "qr_base64": string;

    /**
     * 扫码轮询凭证
     */
    "sign": string;
    "prompt": string;
}

/**
 * BaiduQuotaInfo 网盘容量信息
 */
export interface BaiduQuotaInfo {
    "success": boolean;

    /**
     * 总容量（字节）
     */
    "total": number;

    /**
     * 已用容量（字节）
     */
    "used": number;
    "message"?: string;
}

export interface DownloadSubmitResult {
    "success": boolean;
    "task_id": string;
    "message"?: string;
}

/**
 * DownloadTaskOptions 自定义下载任务选项（前端新建任务弹窗提交）
 */
export interface DownloadTaskOptions {
    "url": string;
    "file_name": string;
    "output_dir": string;
    "connections": number;
    "chunk_kb": number;
    "user_agent": string;
    "proxy": string;
    "headers": { [_ in string]?: string } | null;
    "checksum_type": string;
    "checksum_value": string;
    "skip_tls_verify": boolean;
}

/**
 * OShinDInfo 组件信息（返回给前端）
 */
export interface OShinDInfo {
    /**
     * 是否已安装（文件存在且加载成功）
     */
    "installed": boolean;

    /**
     * 已安装版本；未安装时为 not_installed
     */
    "version": string;

    /**
     * 仓库主页
     */
    "repo_url": string;

    /**
     * 加载失败原因（存在但损坏/不兼容时非空）
     */
    "load_error"?: string;
}

/**
 * OShinDUpdateResult 检查 OShinD 更新结果
 */
export interface OShinDUpdateResult {
    "success": boolean;
    "message": string;
    "current_version"?: string;
    "latest_version": string;
    "has_update": boolean;
    "changelog": string;
    "page_url": string;
}

/**
 * UpdateCheckResult 检查更新结果（返回给前端）
 */
export interface UpdateCheckResult {
    "success": boolean;
    "message": string;
    "current_version": string;
    "latest_version": string;
    "has_update": boolean;
    "changelog": string;
    "page_url": string;
}
