// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppSettings 应用设置结构，JSON 字段即落盘字段
 */
export interface AppSettings {
    /**
     * 程序设置
     * 语言代码，如 zh-CN
     */
    "language": string;

    /**
     * 点击关闭后的操作：exit / tray（预留）
     */
    "close_action": string;

    /**
     * 下载代理（留空不启用）。⚠️ 当前未生效：OShinD 引擎不支持代理配置
     */
    "download_proxy": string;

    /**
     * 下载设置
     * 默认 UA
     */
    "download_user_agent": string;

    /**
     * 默认线程数
     */
    "download_threads": number;

    /**
     * 分片大小（KB，0 表示未设置用默认值）
     */
    "download_chunk_kb": number;

    /**
     * 默认下载目录
     */
    "download_dir": string;

    /**
     * 远程解析加速链接（留空仅本地解析）
     */
    "download_acc_link": string;

    /**
     * 下载失败自动重试次数（0 表示不重试）
     */
    "download_max_retries": number;

    /**
     * 同时下载文件数上限（超出部分排队）
     */
    "download_max_active": number;

    /**
     * 其他
     * 日志等级：debug/info/warn/error
     */
    "log_level": string;
}

/**
 * BaiduDownloadLinkResult 下载地址解析结果（返回给前端）
 */
export interface BaiduDownloadLinkResult {
    "success": boolean;
    "fs_id": number;
    "filename": string;
    "dlink": string;
    "message"?: string;
}

export interface BaiduFileItem {
    "fs_id": number;
    "path": string;
    "filename": string;
    "server_filename": string;
    "size": number;
    "isdir": number;
    "server_mtime": number;
    "category": number;
    "md5"?: string;
}

export interface BaiduFileListResult {
    "success": boolean;
    "dir": string;
    "list": BaiduFileItem[] | null;
    "message"?: string;
}

export interface BaiduLoginResult {
    "success": boolean;
    "username": string;
    "user_id": string;
    "bduss": string;
    "ptoken": string;
    "stoken": string;

    /**
     * 网盘操作用的 bdstoken
     */
    "bd_stoken": string;

    /**
     * 0 无会员 / 1 VIP / 2 SVIP
     */
    "vip_type": number;

    /**
     * 头像
     */
    "photo_url": string;
    "message": string;
}

export interface BaiduPollResult {
    /**
     * waiting | scanned | success | error
     */
    "status": string;

    /**
     * 登录凭证 v（status == success 时有效）
     */
    "v": string;
}

export interface BaiduQRCode {
    /**
     * 二维码图片 Data URL（image/png;base64）
     */
    "qr_base64": string;

    /**
     * 扫码轮询凭证
     */
    "sign": string;
    "prompt": string;
}

/**
 * BaiduQuotaInfo 网盘容量信息
 */
export interface BaiduQuotaInfo {
    "success": boolean;

    /**
     * 总容量（字节）
     */
    "total": number;

    /**
     * 已用容量（字节）
     */
    "used": number;
    "message"?: string;
}

/**
 * BaiduSMSCodeResult 发送短信验证码的结果
 */
export interface BaiduSMSCodeResult {
    "success": boolean;
    "message": string;

    /**
     * 短信验证码位数，默认 6
     */
    "code_length": number;

    /**
     * 需要先填写图形验证码
     */
    "need_vcode": boolean;

    /**
     * 图形验证码图片（Data URL）
     */
    "vcode_image": string;

    /**
     * 图形验证码会话串，重发时原样回传
     */
    "vcode_str": string;

    /**
     * 图形验证码签名，重发时原样回传
     */
    "vcode_sign": string;
}

export interface DownloadSubmitResult {
    "success": boolean;
    "task_id": string;
    "message"?: string;

    /**
     * Queued 任务因并发上限进入排队（TaskID 是 queued-<seq> 占位符，
     * 引擎侧真实 taskID 在调度器递补时才生成）
     */
    "queued"?: boolean;
}

/**
 * DownloadTaskOptions 自定义下载任务选项（前端新建任务弹窗提交）
 */
export interface DownloadTaskOptions {
    "url": string;
    "file_name": string;
    "output_dir": string;
    "connections": number;
    "chunk_kb": number;
    "user_agent": string;
    "proxy": string;
    "headers": { [_ in string]?: string } | null;
    "checksum_type": string;
    "checksum_value": string;
    "skip_tls_verify": boolean;
}

/**
 * OShinDInfo 下载引擎信息（返回给前端）
 */
export interface OShinDInfo {
    "version": string;
    "repo_url": string;
}

/**
 * UpdateCheckResult 检查更新结果（返回给前端）
 */
export interface UpdateCheckResult {
    "success": boolean;
    "message": string;
    "current_version": string;
    "latest_version": string;
    "has_update": boolean;
    "changelog": string;
    "page_url": string;
}
